from pathlib import Path
p=Path('/mnt/data/fix4/public/dashboard-concessionario.html')
s=p.read_text()
# Strong override for global padding/header and smaller kpi, visual comparator
insert='''\n\n    /* Dashboard concessionario: annulla header pubblico globale e spazio superiore */\n    html body {\n      padding-top: 0 !important;\n      margin-top: 0 !important;\n    }\n\n    body > .main-header,\n    body > .premium-header,\n    body > .topbar {\n      display: none !important;\n      height: 0 !important;\n      min-height: 0 !important;\n    }\n\n    .dealer-shell {\n      margin-top: 0 !important;\n    }\n\n    /* KPI più compatti: solo riepilogo dashboard, non tab fissi */\n    .kpi-grid {\n      grid-template-columns: repeat(4, minmax(0, 1fr));\n      gap: 12px !important;\n      margin-bottom: 18px !important;\n    }\n\n    .kpi-card {\n      min-height: 82px !important;\n      padding: 13px 15px !important;\n      border-radius: 15px !important;\n      grid-template-columns: 36px 1fr !important;\n      gap: 12px !important;\n      align-items: center !important;\n    }\n\n    .kpi-icon {\n      width: 36px !important;\n      height: 36px !important;\n      font-size: 14px !important;\n    }\n\n    .kpi-label {\n      font-size: 10px !important;\n      margin-bottom: 5px !important;\n    }\n\n    .kpi-value {\n      font-size: 22px !important;\n      margin-bottom: 3px !important;\n    }\n\n    .kpi-note {\n      font-size: 10px !important;\n    }\n\n    /* Comparatore con più carattere e migliore delimitazione */\n    .comparatore-panel {\n      padding: 34px !important;\n      border: 1px solid rgba(79, 140, 255, 0.34) !important;\n      background:\n        linear-gradient(120deg, rgba(7,29,73,0.96) 0%, rgba(12,44,103,0.94) 45%, rgba(38,95,180,0.88) 100%),\n        radial-gradient(circle at 84% 18%, rgba(24,180,90,0.35), transparent 34%) !important;\n      color: #ffffff !important;\n      box-shadow: 0 26px 70px rgba(7,29,73,0.18) !important;\n    }\n\n    .comparatore-panel::before {\n      width: 9px !important;\n      background: linear-gradient(180deg, #18b45a, #4f8cff, #7b61ff) !important;\n    }\n\n    .comparatore-panel h2,\n    .comparatore-panel .form-group label {\n      color: #ffffff !important;\n    }\n\n    .comparatore-panel p {\n      color: rgba(255,255,255,0.78) !important;\n    }\n\n    .comparatore-panel .badge {\n      background: rgba(255,255,255,0.12) !important;\n      color: #ffffff !important;\n      border: 1px solid rgba(255,255,255,0.18) !important;\n    }\n\n    .comparatore-panel .plate-wrap,\n    .comparatore-panel .form-group input {\n      border-color: rgba(255,255,255,0.22) !important;\n      box-shadow: 0 18px 35px rgba(0,0,0,0.16) !important;\n    }\n'''
# insert before media starts at @media around later or before </style>
s=s.replace('  </style>', insert+'\n  </style>')
# Remove duplicate Panoramica nav and Nuova ricerca nav
s=s.replace('''\n        <button class="nav-item sidebar-section-btn" type="button" data-section="overview">\n          <span class="nav-icon"><i class="fa-solid fa-table-columns"></i></span>\n          Panoramica\n        </button>\n''','')
s=s.replace('''\n        <button class="nav-item sidebar-section-btn" type="button" data-section="search">\n          <span class="nav-icon"><i class="fa-solid fa-magnifying-glass"></i></span>\n          Nuova ricerca\n        </button>\n''','')
# hero button: Nuova ricerca -> Comparatore
s=s.replace('''<button class="hero-btn primary sidebar-section-btn" type="button" data-section="search">\n              <i class="fa-solid fa-magnifying-glass"></i>\n              Nuova ricerca\n            </button>''','''<button class="hero-btn primary sidebar-section-btn" type="button" data-section="comparatore">\n              <i class="fa-solid fa-scale-balanced"></i>\n              Apri comparatore\n            </button>''')
# operation card to search -> comparatore/text
s=s.replace('''<article class="operation-card sidebar-section-btn" data-section="search">\n              <div class="operation-icon"><i class="fa-solid fa-car-side"></i></div>\n              <div>\n                <h3>Nuova ricerca veicolo</h3>\n                <p>Inserisci targa, modello, anno e chilometraggio per confrontare le garanzie compatibili.</p>\n              </div>\n              <div class="operation-arrow">›</div>\n            </article>''','''<article class="operation-card sidebar-section-btn" data-section="comparatore">\n              <div class="operation-icon"><i class="fa-solid fa-scale-balanced"></i></div>\n              <div>\n                <h3>Comparatore garanzie</h3>\n                <p>Inserisci la targa e completa i dati veicolo per confrontare le garanzie compatibili.</p>\n              </div>\n              <div class="operation-arrow">›</div>\n            </article>''')
# vehicles first card to comparatore remove duplicated two cards -> one card + orders maybe
s=s.replace('''<article class="operation-card sidebar-section-btn" data-section="search">\n              <div class="operation-icon"><i class="fa-solid fa-magnifying-glass"></i></div>\n              <div><h3>Nuova ricerca</h3><p>Inserisci targa, modello, anno e chilometri per iniziare.</p></div>\n              <div class="operation-arrow">›</div>\n            </article>\n            <article class="operation-card sidebar-section-btn" data-section="comparatore">\n              <div class="operation-icon"><i class="fa-solid fa-scale-balanced"></i></div>\n              <div><h3>Vai al comparatore</h3><p>Avvia il confronto garanzie partendo dalla targa.</p></div>\n              <div class="operation-arrow">›</div>\n            </article>''','''<article class="operation-card sidebar-section-btn" data-section="comparatore">\n              <div class="operation-icon"><i class="fa-solid fa-scale-balanced"></i></div>\n              <div><h3>Comparatore garanzie</h3><p>Avvia il confronto garanzie partendo dalla targa.</p></div>\n              <div class="operation-arrow">›</div>\n            </article>\n            <article class="operation-card sidebar-section-btn" data-section="orders">\n              <div class="operation-icon"><i class="fa-solid fa-folder-open"></i></div>\n              <div><h3>Veicoli in pratica</h3><p>Consulta i veicoli già presenti nello storico pratiche.</p></div>\n              <div class="operation-arrow">›</div>\n            </article>''')
# Remove the unused section-search from HTML completely to avoid repetition maybe no nav points to it; not necessary but clean
start=s.find('      <section id="section-search" class="section">')
end=s.find('      <section id="section-orders" class="section">')
if start!=-1 and end!=-1:
    s=s[:start]+s[end:]
# fix duplicate partner open if exists
s=s.replace('      <section id="section-partner" class="section">\n      <section id="section-partner" class="section">','      <section id="section-partner" class="section">')
# duplicate Esci
s=s.replace('''Esci <i class="fa-solid fa-arrow-right-from-bracket"></i>\n          Esci <i class="fa-solid fa-arrow-right-from-bracket"></i>''','''Esci <i class="fa-solid fa-arrow-right-from-bracket"></i>''')
p.write_text(s)
